name: docker-build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Restic target version
        id: getversion
        run: |
          export VERSION_RESTIC=$(cat VERSION)
          echo VERSION_RESTIC=${VERSION_RESTIC}
          echo "VERSION_RESTIC=$VERSION_RESTIC" >> $GITHUB_ENV

      - name: Generate tag(s) from GitHub ref
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Log in to ghcr.io registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get image name from lowercased repo name
        run: |
          export IMAGE_NAME="${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=${IMAGE_NAME/\/docker-/\/}" | tee -a ${GITHUB_ENV}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.docker-tag.outputs.tag }}
          push: true
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          build-args: |
            VERSION_RESTIC=${{ env.VERSION_RESTIC }}
